### ISSUE TITLE
Document `--use-cog-base-image`

### ISSUE THREAD

**Issue by zeke** [replicate/cog#1820]
There's a new flag for `cog push` that lets you use prebuilt base images designed specifically for Cog.

Using this flag when pushing your models can **significantly reduce their cold boot time**:

```
cog push --use-cog-base-image r8.im/my-name/my-model
```

For more details, see https://github.com/replicate/cog/pull/1778

## Tasks

- [ ] Add a new doc that explains what prebuilt Cog images are, what's on them, etc.
- [ ] Clarify relationship between `use-cog-base-image` and `use-cuda-base-image`. Are they related? Do they override each other?
    ```
    $ cog push --help | grep base-image
      --use-cog-base-image           Use pre-built Cog base image for faster cold boots (default true)
      --use-cuda-base-image string   Use Nvidia CUDA base image, 'true' (default) or 'false' (use python base image). False results in a smaller image but may cause problems for non-torch projects (default "auto")
      ```
 - [ ] Update getting started docs with correct `cog push` incantations.
